services:
  # Static Web Application Service
  textura:
    container_name: textura-web
    # 使用源码构建静态站点镜像
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - NODE_ENV=production
    networks:
      - textura-net
    # No ports exposed to host, only internal network

  # Nginx Reverse Proxy Service
  nginx:
    image: nginx:alpine
    container_name: textura-nginx
    restart: always
    ports:
      - "80:80"
      # - "443:443" # Uncomment for HTTPS later
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - textura
    networks:
      - textura-net

networks:
  textura-net:
    driver: bridge
